language: node_js
os: linux
dist: xenial
node_js:
- 12
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm test
before_deploy:
- npm run build
deploy:
  provider: npm
  email: emilio.ferrert@gmail.com
  skip_cleanup: 'true'
  api_key:
    secure: g21FwAOXYqg9LqhjB+kX2BvGgzBu3DAnHYaXj4bdK//Wfp9mgPm6sg6TQzxUUdk4QeToPtnKZyRmhCD7w8BaWr0rFP9M25rGqz2Q5Dd1Bs6XK2frxMMJtHWB5btXhO8HRRlHwtXBOw1VIrOReRdIZgh3Z0OgX22oEJm7xhU2oHHmf7RTiBRm0B12+DbhT81DCBFY0lq4eaId3o5ENuD0h4kuzkbGjWRW3ns7bJV//T5rQfem6TBzF58/cWRv3Vo/u+EoqbzjQoZ4dOOfnhHtmUtqNCn9Ud/OGgR6H7XyJLjWVfvd2nHbL88KTmaLqKiE0+Nmz5PZBx22XFonBQREA4lJHdtDyRbQyGRXAIpp4OjeAelsd0or9oUwGD8VY5AU87pXfVFaG0EcWpdcnZj6CWRmB8a/H+hohS6mjrLvMqJOYGOxknS11ygt7EgngQ0YRrSqT5CkD3RUXCuBq8PH3+sfrgX8XoZvBQioycra85zH3S86E31Yxoh1UzE2B7oaIuTe/ppx9JooF/pjfC6GqI0U7UMmfLpnwRKYTOefd9q+LVxzu0C1TvwPWyEaZcIwm9OXtJOrSLYzZ5zh4sI+Kc4VNxvL5DDCsPOC+T65OlCsRvcS+gxUPAAXhd23ED1sIhTVUODCOy4oz9GXlWWD3Wx/6XoF+PQo1lRRUkXiHls=
  on:
    repo: emilio-ferrer/unofficial-klap-sdk-nodejs

