language: node_js
os: linux
dist: xenial
node_js:
- 12
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm test
before_deploy:
- npm run build
deploy:
  provider: npm
  email: emilio.ferrert@gmail.com
  api_token:
    secure: ANy7hd35AuGmjfMB6w9bGkXt6y9LoEiKlBXTFsUVFmVfMTzQcY5UdMbzL74aZpwblJRwZwIIgCg6KF0CwfFlo7ir+G40Yh35ddyoY6lvHsHJ0k2m07g2zWPbZT4equguhowS2pA64GSCu4uOUrswAn0Exhq9KeiWKyISaYZFSs38gN8W4lgjr1n/qTnMeInCKSGv0l0ingyznBNIMqcf3+gwgACK1mZDMk0IOWvy/OB1ljE62et7mW1Yq0sSv8Ttn5ddRQhir9p/+/0ujfOP8leWKASLWEZ0/uIIoiyYrR1azQ/+UjyPSEX1XWbdp83ACQKKJl7pja4IKy66qEr+RZ08teW686tVvSwyT1sPaXNC0EoOoKDOdGO6vE23IQi9C8U0Zo3DUTQUWMrz9P6qCX/N2obQ8ldWv8eD1YYm+358+5MbnXqfNyS+H2dTnbW7I0suGBjqYc6LrBM8keXiuBjuVoGevbdFmh7eIxIV5vad9B88e9PtrvpFiS1CVOoChYcMF1a4vApUmpGpTzmPi1Nh1H81oKgcn3/S+/QwS0verDxJGXqYI69Mh8R6qZL7W9D2mDh85nj7c8RGK6VfIG4VXHtz1nO09rTlyz2w9bCy0FJMH+gvGza9n0HA9cbpWfJqAw3Qn1F7dFdTBiDfFeLQFnsf3ZBIYD1R6ZZmOtY=
  tag: beta
  skip_cleanup: true
  on:
    branch: master
    repo: emilio-ferrer/unofficial-klap-sdk-nodejs
