language: node_js
os: linux
dist: xenial
node_js:
- 11
- 12
- 13
- 14
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm test
before_deploy:
- npm run build
deploy:
  provider: npm
  email: emilio.ferrert+github@gmail.com
  api_key:
    secure: $NPM_TOKEN
  cleanup: true
  on:
    branch: master
    tags: true
    repo: emilio-ferrer/unofficial-klap-sdk-nodejs
