language: node_js
os: linux
dist: xenial
node_js:
- 12
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm test
before_deploy:
- npm run build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  cleanup: true
  on:
    branch: master
    tags: true
    repo: emilio-ferrer/unofficial-klap-sdk-nodejs
